#############################################################################
# Makefile for building: my_project
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  my_project.pro
# Template: app
# Command: /opt/qt5.12.10-arm/bin/qmake -o Makefile my_project.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = aarch64-linux-gnu-gcc
CXX           = aarch64-linux-gnu-g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DPROJECT_SOURCE_DIR=\"/home/master/linux/my_project\" -DQT_NO_DEBUG -DQT_MULTIMEDIAWIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -march=armv8-a -lts -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -march=armv8-a -lts -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/qt5.12.10-arm/include -I/opt/qt5.12.10-arm/include/QtMultimediaWidgets -I/opt/qt5.12.10-arm/include/QtMultimedia -I/opt/qt5.12.10-arm/include/QtWidgets -I/opt/qt5.12.10-arm/include/QtGui -I/opt/qt5.12.10-arm/include/QtNetwork -I/opt/qt5.12.10-arm/include/QtCore -I. -I. -I/opt/qt5.12.10-arm/mkspecs/linux-aarch64-gnu-g++
QMAKE         = /opt/qt5.12.10-arm/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/qt5.12.10-arm/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/qt5.12.10-arm/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = my_project1.0.0
DISTDIR = /home/master/linux/my_project/.tmp/my_project1.0.0
LINK          = aarch64-linux-gnu-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/qt5.12.10-arm/lib
LIBS          = $(SUBLIBS) /opt/qt5.12.10-arm/lib/libQt5MultimediaWidgets.so /opt/qt5.12.10-arm/lib/libQt5Multimedia.so /opt/qt5.12.10-arm/lib/libQt5Widgets.so /opt/qt5.12.10-arm/lib/libQt5Gui.so /opt/qt5.12.10-arm/lib/libQt5Network.so /opt/qt5.12.10-arm/lib/libQt5Core.so -lpthread   
AR            = aarch64-linux-gnu-ar cqs
RANLIB        = 
SED           = sed
STRIP         = aarch64-linux-gnu-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = camerathread.cpp \
		dialog.cpp \
		main.cpp \
		cam.cpp \
		v4l2_app.c moc_cam.cpp \
		moc_camerathread.cpp \
		moc_dialog.cpp
OBJECTS       = camerathread.o \
		dialog.o \
		main.o \
		cam.o \
		v4l2_app.o \
		moc_cam.o \
		moc_camerathread.o \
		moc_dialog.o
DIST          = img/20260419_153348.jpg \
		/opt/qt5.12.10-arm/mkspecs/features/spec_pre.prf \
		/opt/qt5.12.10-arm/mkspecs/common/unix.conf \
		/opt/qt5.12.10-arm/mkspecs/common/linux.conf \
		/opt/qt5.12.10-arm/mkspecs/common/sanitize.conf \
		/opt/qt5.12.10-arm/mkspecs/common/gcc-base.conf \
		/opt/qt5.12.10-arm/mkspecs/common/gcc-base-unix.conf \
		/opt/qt5.12.10-arm/mkspecs/common/g++-base.conf \
		/opt/qt5.12.10-arm/mkspecs/common/g++-unix.conf \
		/opt/qt5.12.10-arm/mkspecs/qconfig.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_charts.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_core.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_help.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_location.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_location_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_network.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_repparser.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_script.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_scxml.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_webview.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/qt5.12.10-arm/mkspecs/features/qt_functions.prf \
		/opt/qt5.12.10-arm/mkspecs/features/qt_config.prf \
		/opt/qt5.12.10-arm/mkspecs/linux-aarch64-gnu-g++/qmake.conf \
		/opt/qt5.12.10-arm/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/qt5.12.10-arm/mkspecs/features/exclusive_builds.prf \
		/opt/qt5.12.10-arm/mkspecs/features/toolchain.prf \
		/opt/qt5.12.10-arm/mkspecs/features/default_pre.prf \
		/opt/qt5.12.10-arm/mkspecs/features/resolve_config.prf \
		/opt/qt5.12.10-arm/mkspecs/features/default_post.prf \
		/opt/qt5.12.10-arm/mkspecs/features/warn_on.prf \
		/opt/qt5.12.10-arm/mkspecs/features/qt.prf \
		/opt/qt5.12.10-arm/mkspecs/features/resources.prf \
		/opt/qt5.12.10-arm/mkspecs/features/moc.prf \
		/opt/qt5.12.10-arm/mkspecs/features/uic.prf \
		/opt/qt5.12.10-arm/mkspecs/features/unix/thread.prf \
		/opt/qt5.12.10-arm/mkspecs/features/qmake_use.prf \
		/opt/qt5.12.10-arm/mkspecs/features/file_copies.prf \
		/opt/qt5.12.10-arm/mkspecs/features/testcase_targets.prf \
		/opt/qt5.12.10-arm/mkspecs/features/exceptions.prf \
		/opt/qt5.12.10-arm/mkspecs/features/yacc.prf \
		/opt/qt5.12.10-arm/mkspecs/features/lex.prf \
		my_project.pro cam.h \
		camerathread.h \
		dialog.h \
		v4l2_app.h camerathread.cpp \
		dialog.cpp \
		main.cpp \
		cam.cpp \
		v4l2_app.c
QMAKE_TARGET  = my_project
DESTDIR       = 
TARGET        = my_project


first: all
####### Build rules

my_project: ui_cam.h ui_dialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: my_project.pro /opt/qt5.12.10-arm/mkspecs/linux-aarch64-gnu-g++/qmake.conf /opt/qt5.12.10-arm/mkspecs/features/spec_pre.prf \
		/opt/qt5.12.10-arm/mkspecs/common/unix.conf \
		/opt/qt5.12.10-arm/mkspecs/common/linux.conf \
		/opt/qt5.12.10-arm/mkspecs/common/sanitize.conf \
		/opt/qt5.12.10-arm/mkspecs/common/gcc-base.conf \
		/opt/qt5.12.10-arm/mkspecs/common/gcc-base-unix.conf \
		/opt/qt5.12.10-arm/mkspecs/common/g++-base.conf \
		/opt/qt5.12.10-arm/mkspecs/common/g++-unix.conf \
		/opt/qt5.12.10-arm/mkspecs/qconfig.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_charts.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_core.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_gui.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_help.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_location.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_location_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_network.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_qml.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_quick.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_repparser.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_script.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_scxml.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_sql.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_svg.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_webview.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_xml.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/qt5.12.10-arm/mkspecs/features/qt_functions.prf \
		/opt/qt5.12.10-arm/mkspecs/features/qt_config.prf \
		/opt/qt5.12.10-arm/mkspecs/linux-aarch64-gnu-g++/qmake.conf \
		/opt/qt5.12.10-arm/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/qt5.12.10-arm/mkspecs/features/exclusive_builds.prf \
		/opt/qt5.12.10-arm/mkspecs/features/toolchain.prf \
		/opt/qt5.12.10-arm/mkspecs/features/default_pre.prf \
		/opt/qt5.12.10-arm/mkspecs/features/resolve_config.prf \
		/opt/qt5.12.10-arm/mkspecs/features/default_post.prf \
		/opt/qt5.12.10-arm/mkspecs/features/warn_on.prf \
		/opt/qt5.12.10-arm/mkspecs/features/qt.prf \
		/opt/qt5.12.10-arm/mkspecs/features/resources.prf \
		/opt/qt5.12.10-arm/mkspecs/features/moc.prf \
		/opt/qt5.12.10-arm/mkspecs/features/uic.prf \
		/opt/qt5.12.10-arm/mkspecs/features/unix/thread.prf \
		/opt/qt5.12.10-arm/mkspecs/features/qmake_use.prf \
		/opt/qt5.12.10-arm/mkspecs/features/file_copies.prf \
		/opt/qt5.12.10-arm/mkspecs/features/testcase_targets.prf \
		/opt/qt5.12.10-arm/mkspecs/features/exceptions.prf \
		/opt/qt5.12.10-arm/mkspecs/features/yacc.prf \
		/opt/qt5.12.10-arm/mkspecs/features/lex.prf \
		my_project.pro
	$(QMAKE) -o Makefile my_project.pro
/opt/qt5.12.10-arm/mkspecs/features/spec_pre.prf:
/opt/qt5.12.10-arm/mkspecs/common/unix.conf:
/opt/qt5.12.10-arm/mkspecs/common/linux.conf:
/opt/qt5.12.10-arm/mkspecs/common/sanitize.conf:
/opt/qt5.12.10-arm/mkspecs/common/gcc-base.conf:
/opt/qt5.12.10-arm/mkspecs/common/gcc-base-unix.conf:
/opt/qt5.12.10-arm/mkspecs/common/g++-base.conf:
/opt/qt5.12.10-arm/mkspecs/common/g++-unix.conf:
/opt/qt5.12.10-arm/mkspecs/qconfig.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_charts.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_charts_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_core.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_core_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_edid_support_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_gui.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_gui_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_help.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_help_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_input_support_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_location.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_location_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_multimedia.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_network.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_network_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_networkauth.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_networkauth_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_nfc.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_positioning.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_positioningquick.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_positioningquick_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_purchasing.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_purchasing_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_qml.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_qml_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_qmltest.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_quick.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_quick_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_quickshapes_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_quicktemplates2.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_remoteobjects.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_repparser.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_repparser_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_script.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_script_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_scripttools.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_scxml.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_sensors.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_serialbus.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_serialport.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_sql.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_sql_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_svg.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_svg_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_testlib.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_texttospeech.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_texttospeech_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_uitools.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_webchannel.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_websockets.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_webview.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_webview_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_widgets.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_xml.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_xml_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/qt5.12.10-arm/mkspecs/modules/qt_lib_zlib_private.pri:
/opt/qt5.12.10-arm/mkspecs/features/qt_functions.prf:
/opt/qt5.12.10-arm/mkspecs/features/qt_config.prf:
/opt/qt5.12.10-arm/mkspecs/linux-aarch64-gnu-g++/qmake.conf:
/opt/qt5.12.10-arm/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/qt5.12.10-arm/mkspecs/features/exclusive_builds.prf:
/opt/qt5.12.10-arm/mkspecs/features/toolchain.prf:
/opt/qt5.12.10-arm/mkspecs/features/default_pre.prf:
/opt/qt5.12.10-arm/mkspecs/features/resolve_config.prf:
/opt/qt5.12.10-arm/mkspecs/features/default_post.prf:
/opt/qt5.12.10-arm/mkspecs/features/warn_on.prf:
/opt/qt5.12.10-arm/mkspecs/features/qt.prf:
/opt/qt5.12.10-arm/mkspecs/features/resources.prf:
/opt/qt5.12.10-arm/mkspecs/features/moc.prf:
/opt/qt5.12.10-arm/mkspecs/features/uic.prf:
/opt/qt5.12.10-arm/mkspecs/features/unix/thread.prf:
/opt/qt5.12.10-arm/mkspecs/features/qmake_use.prf:
/opt/qt5.12.10-arm/mkspecs/features/file_copies.prf:
/opt/qt5.12.10-arm/mkspecs/features/testcase_targets.prf:
/opt/qt5.12.10-arm/mkspecs/features/exceptions.prf:
/opt/qt5.12.10-arm/mkspecs/features/yacc.prf:
/opt/qt5.12.10-arm/mkspecs/features/lex.prf:
my_project.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile my_project.pro

qmake_all: FORCE


all: Makefile my_project

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /opt/qt5.12.10-arm/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents cam.h camerathread.h dialog.h v4l2_app.h $(DISTDIR)/
	$(COPY_FILE) --parents camerathread.cpp dialog.cpp main.cpp cam.cpp v4l2_app.c $(DISTDIR)/
	$(COPY_FILE) --parents cam.ui dialog.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/qt5.12.10-arm/mkspecs/features/data/dummy.cpp
	aarch64-linux-gnu-g++ -pipe -O2 -march=armv8-a -lts -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /opt/qt5.12.10-arm/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_cam.cpp moc_camerathread.cpp moc_dialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_cam.cpp moc_camerathread.cpp moc_dialog.cpp
moc_cam.cpp: cam.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QWidget \
		/opt/qt5.12.10-arm/include/QtWidgets/qwidget.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qtwidgetsglobal.h \
		/opt/qt5.12.10-arm/include/QtGui/qtguiglobal.h \
		/opt/qt5.12.10-arm/include/QtCore/qglobal.h \
		/opt/qt5.12.10-arm/include/QtCore/qconfig-bootstrapped.h \
		/opt/qt5.12.10-arm/include/QtCore/qconfig.h \
		/opt/qt5.12.10-arm/include/QtCore/qtcore-config.h \
		/opt/qt5.12.10-arm/include/QtCore/qsystemdetection.h \
		/opt/qt5.12.10-arm/include/QtCore/qprocessordetection.h \
		/opt/qt5.12.10-arm/include/QtCore/qcompilerdetection.h \
		/opt/qt5.12.10-arm/include/QtCore/qtypeinfo.h \
		/opt/qt5.12.10-arm/include/QtCore/qsysinfo.h \
		/opt/qt5.12.10-arm/include/QtCore/qlogging.h \
		/opt/qt5.12.10-arm/include/QtCore/qflags.h \
		/opt/qt5.12.10-arm/include/QtCore/qatomic.h \
		/opt/qt5.12.10-arm/include/QtCore/qbasicatomic.h \
		/opt/qt5.12.10-arm/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5.12.10-arm/include/QtCore/qgenericatomic.h \
		/opt/qt5.12.10-arm/include/QtCore/qatomic_cxx11.h \
		/opt/qt5.12.10-arm/include/QtCore/qatomic_msvc.h \
		/opt/qt5.12.10-arm/include/QtCore/qglobalstatic.h \
		/opt/qt5.12.10-arm/include/QtCore/qmutex.h \
		/opt/qt5.12.10-arm/include/QtCore/qnumeric.h \
		/opt/qt5.12.10-arm/include/QtCore/qversiontagging.h \
		/opt/qt5.12.10-arm/include/QtGui/qtgui-config.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qtwidgets-config.h \
		/opt/qt5.12.10-arm/include/QtGui/qwindowdefs.h \
		/opt/qt5.12.10-arm/include/QtCore/qobjectdefs.h \
		/opt/qt5.12.10-arm/include/QtCore/qnamespace.h \
		/opt/qt5.12.10-arm/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5.12.10-arm/include/QtGui/qwindowdefs_win.h \
		/opt/qt5.12.10-arm/include/QtCore/qobject.h \
		/opt/qt5.12.10-arm/include/QtCore/qstring.h \
		/opt/qt5.12.10-arm/include/QtCore/qchar.h \
		/opt/qt5.12.10-arm/include/QtCore/qbytearray.h \
		/opt/qt5.12.10-arm/include/QtCore/qrefcount.h \
		/opt/qt5.12.10-arm/include/QtCore/qarraydata.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringliteral.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringalgorithms.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringview.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringbuilder.h \
		/opt/qt5.12.10-arm/include/QtCore/qlist.h \
		/opt/qt5.12.10-arm/include/QtCore/qalgorithms.h \
		/opt/qt5.12.10-arm/include/QtCore/qiterator.h \
		/opt/qt5.12.10-arm/include/QtCore/qhashfunctions.h \
		/opt/qt5.12.10-arm/include/QtCore/qpair.h \
		/opt/qt5.12.10-arm/include/QtCore/qbytearraylist.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringlist.h \
		/opt/qt5.12.10-arm/include/QtCore/qregexp.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringmatcher.h \
		/opt/qt5.12.10-arm/include/QtCore/qcoreevent.h \
		/opt/qt5.12.10-arm/include/QtCore/qscopedpointer.h \
		/opt/qt5.12.10-arm/include/QtCore/qmetatype.h \
		/opt/qt5.12.10-arm/include/QtCore/qvarlengtharray.h \
		/opt/qt5.12.10-arm/include/QtCore/qcontainerfwd.h \
		/opt/qt5.12.10-arm/include/QtCore/qobject_impl.h \
		/opt/qt5.12.10-arm/include/QtCore/qmargins.h \
		/opt/qt5.12.10-arm/include/QtGui/qpaintdevice.h \
		/opt/qt5.12.10-arm/include/QtCore/qrect.h \
		/opt/qt5.12.10-arm/include/QtCore/qsize.h \
		/opt/qt5.12.10-arm/include/QtCore/qpoint.h \
		/opt/qt5.12.10-arm/include/QtGui/qpalette.h \
		/opt/qt5.12.10-arm/include/QtGui/qcolor.h \
		/opt/qt5.12.10-arm/include/QtGui/qrgb.h \
		/opt/qt5.12.10-arm/include/QtGui/qrgba64.h \
		/opt/qt5.12.10-arm/include/QtGui/qbrush.h \
		/opt/qt5.12.10-arm/include/QtCore/qvector.h \
		/opt/qt5.12.10-arm/include/QtGui/qmatrix.h \
		/opt/qt5.12.10-arm/include/QtGui/qpolygon.h \
		/opt/qt5.12.10-arm/include/QtGui/qregion.h \
		/opt/qt5.12.10-arm/include/QtCore/qdatastream.h \
		/opt/qt5.12.10-arm/include/QtCore/qiodevice.h \
		/opt/qt5.12.10-arm/include/QtCore/qline.h \
		/opt/qt5.12.10-arm/include/QtGui/qtransform.h \
		/opt/qt5.12.10-arm/include/QtGui/qpainterpath.h \
		/opt/qt5.12.10-arm/include/QtGui/qimage.h \
		/opt/qt5.12.10-arm/include/QtGui/qpixelformat.h \
		/opt/qt5.12.10-arm/include/QtGui/qpixmap.h \
		/opt/qt5.12.10-arm/include/QtCore/qsharedpointer.h \
		/opt/qt5.12.10-arm/include/QtCore/qshareddata.h \
		/opt/qt5.12.10-arm/include/QtCore/qhash.h \
		/opt/qt5.12.10-arm/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5.12.10-arm/include/QtGui/qfont.h \
		/opt/qt5.12.10-arm/include/QtGui/qfontmetrics.h \
		/opt/qt5.12.10-arm/include/QtGui/qfontinfo.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qsizepolicy.h \
		/opt/qt5.12.10-arm/include/QtGui/qcursor.h \
		/opt/qt5.12.10-arm/include/QtGui/qkeysequence.h \
		/opt/qt5.12.10-arm/include/QtGui/qevent.h \
		/opt/qt5.12.10-arm/include/QtCore/qvariant.h \
		/opt/qt5.12.10-arm/include/QtCore/qmap.h \
		/opt/qt5.12.10-arm/include/QtCore/qdebug.h \
		/opt/qt5.12.10-arm/include/QtCore/qtextstream.h \
		/opt/qt5.12.10-arm/include/QtCore/qlocale.h \
		/opt/qt5.12.10-arm/include/QtCore/qset.h \
		/opt/qt5.12.10-arm/include/QtCore/qcontiguouscache.h \
		/opt/qt5.12.10-arm/include/QtCore/qurl.h \
		/opt/qt5.12.10-arm/include/QtCore/qurlquery.h \
		/opt/qt5.12.10-arm/include/QtCore/qfile.h \
		/opt/qt5.12.10-arm/include/QtCore/qfiledevice.h \
		/opt/qt5.12.10-arm/include/QtGui/qvector2d.h \
		/opt/qt5.12.10-arm/include/QtGui/qtouchdevice.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/QCamera \
		/opt/qt5.12.10-arm/include/QtMultimedia/qcamera.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qmediacontrol.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qtmultimediaglobal.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qtmultimedia-config.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qmediaobject.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qmultimedia.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qmediaservice.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qcameraexposure.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qmediaenumdebug.h \
		/opt/qt5.12.10-arm/include/QtCore/qmetaobject.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qcamerafocus.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qcameraimageprocessing.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qcameraviewfindersettings.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qvideoframe.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qabstractvideobuffer.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/QCameraImageCapture \
		/opt/qt5.12.10-arm/include/QtMultimedia/qcameraimagecapture.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qmediaencodersettings.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qmediabindableinterface.h \
		/opt/qt5.12.10-arm/include/QtMultimediaWidgets/QVideoWidget \
		/opt/qt5.12.10-arm/include/QtMultimediaWidgets/qvideowidget.h \
		/opt/qt5.12.10-arm/include/QtMultimediaWidgets/qtmultimediawidgetdefs.h \
		/opt/qt5.12.10-arm/include/QtCore/QDateTime \
		/opt/qt5.12.10-arm/include/QtCore/qdatetime.h \
		/opt/qt5.12.10-arm/include/QtCore/QDir \
		/opt/qt5.12.10-arm/include/QtCore/qdir.h \
		/opt/qt5.12.10-arm/include/QtCore/qfileinfo.h \
		/opt/qt5.12.10-arm/include/QtCore/QTimer \
		/opt/qt5.12.10-arm/include/QtCore/qtimer.h \
		/opt/qt5.12.10-arm/include/QtCore/qbasictimer.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/QVideoProbe \
		/opt/qt5.12.10-arm/include/QtMultimedia/qvideoprobe.h \
		/opt/qt5.12.10-arm/include/QtCore/QObject \
		/opt/qt5.12.10-arm/include/QtWidgets/QGraphicsScene \
		/opt/qt5.12.10-arm/include/QtWidgets/qgraphicsscene.h \
		/opt/qt5.12.10-arm/include/QtGui/qpen.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QGraphicsView \
		/opt/qt5.12.10-arm/include/QtWidgets/qgraphicsview.h \
		/opt/qt5.12.10-arm/include/QtGui/qpainter.h \
		/opt/qt5.12.10-arm/include/QtGui/qtextoption.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qscrollarea.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qabstractscrollarea.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qframe.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QGraphicsProxyWidget \
		/opt/qt5.12.10-arm/include/QtWidgets/qgraphicsproxywidget.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qgraphicswidget.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qgraphicslayoutitem.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qgraphicsitem.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QApplication \
		/opt/qt5.12.10-arm/include/QtWidgets/qapplication.h \
		/opt/qt5.12.10-arm/include/QtCore/qcoreapplication.h \
		/opt/qt5.12.10-arm/include/QtCore/qeventloop.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qdesktopwidget.h \
		/opt/qt5.12.10-arm/include/QtGui/qguiapplication.h \
		/opt/qt5.12.10-arm/include/QtGui/qinputmethod.h \
		/opt/qt5.12.10-arm/include/QtMultimediaWidgets/QGraphicsVideoItem \
		/opt/qt5.12.10-arm/include/QtMultimediaWidgets/qgraphicsvideoitem.h \
		camerathread.h \
		/opt/qt5.12.10-arm/include/QtCore/QThread \
		/opt/qt5.12.10-arm/include/QtCore/qthread.h \
		/opt/qt5.12.10-arm/include/QtGui/QImage \
		moc_predefs.h \
		/opt/qt5.12.10-arm/bin/moc
	/opt/qt5.12.10-arm/bin/moc $(DEFINES) --include /home/master/linux/my_project/moc_predefs.h -I/opt/qt5.12.10-arm/mkspecs/linux-aarch64-gnu-g++ -I/home/master/linux/my_project -I/opt/qt5.12.10-arm/include -I/opt/qt5.12.10-arm/include/QtMultimediaWidgets -I/opt/qt5.12.10-arm/include/QtMultimedia -I/opt/qt5.12.10-arm/include/QtWidgets -I/opt/qt5.12.10-arm/include/QtGui -I/opt/qt5.12.10-arm/include/QtNetwork -I/opt/qt5.12.10-arm/include/QtCore -I/usr/aarch64-linux-gnu/include/c++/9 -I/usr/aarch64-linux-gnu/include/c++/9/aarch64-linux-gnu -I/usr/aarch64-linux-gnu/include/c++/9/backward -I/usr/lib/gcc-cross/aarch64-linux-gnu/9/include -I/usr/aarch64-linux-gnu/include -I/usr/include cam.h -o moc_cam.cpp

moc_camerathread.cpp: camerathread.h \
		/opt/qt5.12.10-arm/include/QtCore/QThread \
		/opt/qt5.12.10-arm/include/QtCore/qthread.h \
		/opt/qt5.12.10-arm/include/QtCore/qobject.h \
		/opt/qt5.12.10-arm/include/QtCore/qobjectdefs.h \
		/opt/qt5.12.10-arm/include/QtCore/qnamespace.h \
		/opt/qt5.12.10-arm/include/QtCore/qglobal.h \
		/opt/qt5.12.10-arm/include/QtCore/qconfig-bootstrapped.h \
		/opt/qt5.12.10-arm/include/QtCore/qconfig.h \
		/opt/qt5.12.10-arm/include/QtCore/qtcore-config.h \
		/opt/qt5.12.10-arm/include/QtCore/qsystemdetection.h \
		/opt/qt5.12.10-arm/include/QtCore/qprocessordetection.h \
		/opt/qt5.12.10-arm/include/QtCore/qcompilerdetection.h \
		/opt/qt5.12.10-arm/include/QtCore/qtypeinfo.h \
		/opt/qt5.12.10-arm/include/QtCore/qsysinfo.h \
		/opt/qt5.12.10-arm/include/QtCore/qlogging.h \
		/opt/qt5.12.10-arm/include/QtCore/qflags.h \
		/opt/qt5.12.10-arm/include/QtCore/qatomic.h \
		/opt/qt5.12.10-arm/include/QtCore/qbasicatomic.h \
		/opt/qt5.12.10-arm/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5.12.10-arm/include/QtCore/qgenericatomic.h \
		/opt/qt5.12.10-arm/include/QtCore/qatomic_cxx11.h \
		/opt/qt5.12.10-arm/include/QtCore/qatomic_msvc.h \
		/opt/qt5.12.10-arm/include/QtCore/qglobalstatic.h \
		/opt/qt5.12.10-arm/include/QtCore/qmutex.h \
		/opt/qt5.12.10-arm/include/QtCore/qnumeric.h \
		/opt/qt5.12.10-arm/include/QtCore/qversiontagging.h \
		/opt/qt5.12.10-arm/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5.12.10-arm/include/QtCore/qstring.h \
		/opt/qt5.12.10-arm/include/QtCore/qchar.h \
		/opt/qt5.12.10-arm/include/QtCore/qbytearray.h \
		/opt/qt5.12.10-arm/include/QtCore/qrefcount.h \
		/opt/qt5.12.10-arm/include/QtCore/qarraydata.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringliteral.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringalgorithms.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringview.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringbuilder.h \
		/opt/qt5.12.10-arm/include/QtCore/qlist.h \
		/opt/qt5.12.10-arm/include/QtCore/qalgorithms.h \
		/opt/qt5.12.10-arm/include/QtCore/qiterator.h \
		/opt/qt5.12.10-arm/include/QtCore/qhashfunctions.h \
		/opt/qt5.12.10-arm/include/QtCore/qpair.h \
		/opt/qt5.12.10-arm/include/QtCore/qbytearraylist.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringlist.h \
		/opt/qt5.12.10-arm/include/QtCore/qregexp.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringmatcher.h \
		/opt/qt5.12.10-arm/include/QtCore/qcoreevent.h \
		/opt/qt5.12.10-arm/include/QtCore/qscopedpointer.h \
		/opt/qt5.12.10-arm/include/QtCore/qmetatype.h \
		/opt/qt5.12.10-arm/include/QtCore/qvarlengtharray.h \
		/opt/qt5.12.10-arm/include/QtCore/qcontainerfwd.h \
		/opt/qt5.12.10-arm/include/QtCore/qobject_impl.h \
		/opt/qt5.12.10-arm/include/QtGui/QImage \
		/opt/qt5.12.10-arm/include/QtGui/qimage.h \
		/opt/qt5.12.10-arm/include/QtGui/qtguiglobal.h \
		/opt/qt5.12.10-arm/include/QtGui/qtgui-config.h \
		/opt/qt5.12.10-arm/include/QtGui/qcolor.h \
		/opt/qt5.12.10-arm/include/QtGui/qrgb.h \
		/opt/qt5.12.10-arm/include/QtGui/qrgba64.h \
		/opt/qt5.12.10-arm/include/QtGui/qpaintdevice.h \
		/opt/qt5.12.10-arm/include/QtGui/qwindowdefs.h \
		/opt/qt5.12.10-arm/include/QtGui/qwindowdefs_win.h \
		/opt/qt5.12.10-arm/include/QtCore/qrect.h \
		/opt/qt5.12.10-arm/include/QtCore/qmargins.h \
		/opt/qt5.12.10-arm/include/QtCore/qsize.h \
		/opt/qt5.12.10-arm/include/QtCore/qpoint.h \
		/opt/qt5.12.10-arm/include/QtGui/qpixelformat.h \
		/opt/qt5.12.10-arm/include/QtGui/qtransform.h \
		/opt/qt5.12.10-arm/include/QtGui/qmatrix.h \
		/opt/qt5.12.10-arm/include/QtGui/qpolygon.h \
		/opt/qt5.12.10-arm/include/QtCore/qvector.h \
		/opt/qt5.12.10-arm/include/QtGui/qregion.h \
		/opt/qt5.12.10-arm/include/QtCore/qdatastream.h \
		/opt/qt5.12.10-arm/include/QtCore/qiodevice.h \
		/opt/qt5.12.10-arm/include/QtCore/qline.h \
		/opt/qt5.12.10-arm/include/QtGui/qpainterpath.h \
		moc_predefs.h \
		/opt/qt5.12.10-arm/bin/moc
	/opt/qt5.12.10-arm/bin/moc $(DEFINES) --include /home/master/linux/my_project/moc_predefs.h -I/opt/qt5.12.10-arm/mkspecs/linux-aarch64-gnu-g++ -I/home/master/linux/my_project -I/opt/qt5.12.10-arm/include -I/opt/qt5.12.10-arm/include/QtMultimediaWidgets -I/opt/qt5.12.10-arm/include/QtMultimedia -I/opt/qt5.12.10-arm/include/QtWidgets -I/opt/qt5.12.10-arm/include/QtGui -I/opt/qt5.12.10-arm/include/QtNetwork -I/opt/qt5.12.10-arm/include/QtCore -I/usr/aarch64-linux-gnu/include/c++/9 -I/usr/aarch64-linux-gnu/include/c++/9/aarch64-linux-gnu -I/usr/aarch64-linux-gnu/include/c++/9/backward -I/usr/lib/gcc-cross/aarch64-linux-gnu/9/include -I/usr/aarch64-linux-gnu/include -I/usr/include camerathread.h -o moc_camerathread.cpp

moc_dialog.cpp: dialog.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QDialog \
		/opt/qt5.12.10-arm/include/QtWidgets/qdialog.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qtwidgetsglobal.h \
		/opt/qt5.12.10-arm/include/QtGui/qtguiglobal.h \
		/opt/qt5.12.10-arm/include/QtCore/qglobal.h \
		/opt/qt5.12.10-arm/include/QtCore/qconfig-bootstrapped.h \
		/opt/qt5.12.10-arm/include/QtCore/qconfig.h \
		/opt/qt5.12.10-arm/include/QtCore/qtcore-config.h \
		/opt/qt5.12.10-arm/include/QtCore/qsystemdetection.h \
		/opt/qt5.12.10-arm/include/QtCore/qprocessordetection.h \
		/opt/qt5.12.10-arm/include/QtCore/qcompilerdetection.h \
		/opt/qt5.12.10-arm/include/QtCore/qtypeinfo.h \
		/opt/qt5.12.10-arm/include/QtCore/qsysinfo.h \
		/opt/qt5.12.10-arm/include/QtCore/qlogging.h \
		/opt/qt5.12.10-arm/include/QtCore/qflags.h \
		/opt/qt5.12.10-arm/include/QtCore/qatomic.h \
		/opt/qt5.12.10-arm/include/QtCore/qbasicatomic.h \
		/opt/qt5.12.10-arm/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5.12.10-arm/include/QtCore/qgenericatomic.h \
		/opt/qt5.12.10-arm/include/QtCore/qatomic_cxx11.h \
		/opt/qt5.12.10-arm/include/QtCore/qatomic_msvc.h \
		/opt/qt5.12.10-arm/include/QtCore/qglobalstatic.h \
		/opt/qt5.12.10-arm/include/QtCore/qmutex.h \
		/opt/qt5.12.10-arm/include/QtCore/qnumeric.h \
		/opt/qt5.12.10-arm/include/QtCore/qversiontagging.h \
		/opt/qt5.12.10-arm/include/QtGui/qtgui-config.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qtwidgets-config.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qwidget.h \
		/opt/qt5.12.10-arm/include/QtGui/qwindowdefs.h \
		/opt/qt5.12.10-arm/include/QtCore/qobjectdefs.h \
		/opt/qt5.12.10-arm/include/QtCore/qnamespace.h \
		/opt/qt5.12.10-arm/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5.12.10-arm/include/QtGui/qwindowdefs_win.h \
		/opt/qt5.12.10-arm/include/QtCore/qobject.h \
		/opt/qt5.12.10-arm/include/QtCore/qstring.h \
		/opt/qt5.12.10-arm/include/QtCore/qchar.h \
		/opt/qt5.12.10-arm/include/QtCore/qbytearray.h \
		/opt/qt5.12.10-arm/include/QtCore/qrefcount.h \
		/opt/qt5.12.10-arm/include/QtCore/qarraydata.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringliteral.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringalgorithms.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringview.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringbuilder.h \
		/opt/qt5.12.10-arm/include/QtCore/qlist.h \
		/opt/qt5.12.10-arm/include/QtCore/qalgorithms.h \
		/opt/qt5.12.10-arm/include/QtCore/qiterator.h \
		/opt/qt5.12.10-arm/include/QtCore/qhashfunctions.h \
		/opt/qt5.12.10-arm/include/QtCore/qpair.h \
		/opt/qt5.12.10-arm/include/QtCore/qbytearraylist.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringlist.h \
		/opt/qt5.12.10-arm/include/QtCore/qregexp.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringmatcher.h \
		/opt/qt5.12.10-arm/include/QtCore/qcoreevent.h \
		/opt/qt5.12.10-arm/include/QtCore/qscopedpointer.h \
		/opt/qt5.12.10-arm/include/QtCore/qmetatype.h \
		/opt/qt5.12.10-arm/include/QtCore/qvarlengtharray.h \
		/opt/qt5.12.10-arm/include/QtCore/qcontainerfwd.h \
		/opt/qt5.12.10-arm/include/QtCore/qobject_impl.h \
		/opt/qt5.12.10-arm/include/QtCore/qmargins.h \
		/opt/qt5.12.10-arm/include/QtGui/qpaintdevice.h \
		/opt/qt5.12.10-arm/include/QtCore/qrect.h \
		/opt/qt5.12.10-arm/include/QtCore/qsize.h \
		/opt/qt5.12.10-arm/include/QtCore/qpoint.h \
		/opt/qt5.12.10-arm/include/QtGui/qpalette.h \
		/opt/qt5.12.10-arm/include/QtGui/qcolor.h \
		/opt/qt5.12.10-arm/include/QtGui/qrgb.h \
		/opt/qt5.12.10-arm/include/QtGui/qrgba64.h \
		/opt/qt5.12.10-arm/include/QtGui/qbrush.h \
		/opt/qt5.12.10-arm/include/QtCore/qvector.h \
		/opt/qt5.12.10-arm/include/QtGui/qmatrix.h \
		/opt/qt5.12.10-arm/include/QtGui/qpolygon.h \
		/opt/qt5.12.10-arm/include/QtGui/qregion.h \
		/opt/qt5.12.10-arm/include/QtCore/qdatastream.h \
		/opt/qt5.12.10-arm/include/QtCore/qiodevice.h \
		/opt/qt5.12.10-arm/include/QtCore/qline.h \
		/opt/qt5.12.10-arm/include/QtGui/qtransform.h \
		/opt/qt5.12.10-arm/include/QtGui/qpainterpath.h \
		/opt/qt5.12.10-arm/include/QtGui/qimage.h \
		/opt/qt5.12.10-arm/include/QtGui/qpixelformat.h \
		/opt/qt5.12.10-arm/include/QtGui/qpixmap.h \
		/opt/qt5.12.10-arm/include/QtCore/qsharedpointer.h \
		/opt/qt5.12.10-arm/include/QtCore/qshareddata.h \
		/opt/qt5.12.10-arm/include/QtCore/qhash.h \
		/opt/qt5.12.10-arm/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5.12.10-arm/include/QtGui/qfont.h \
		/opt/qt5.12.10-arm/include/QtGui/qfontmetrics.h \
		/opt/qt5.12.10-arm/include/QtGui/qfontinfo.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qsizepolicy.h \
		/opt/qt5.12.10-arm/include/QtGui/qcursor.h \
		/opt/qt5.12.10-arm/include/QtGui/qkeysequence.h \
		/opt/qt5.12.10-arm/include/QtGui/qevent.h \
		/opt/qt5.12.10-arm/include/QtCore/qvariant.h \
		/opt/qt5.12.10-arm/include/QtCore/qmap.h \
		/opt/qt5.12.10-arm/include/QtCore/qdebug.h \
		/opt/qt5.12.10-arm/include/QtCore/qtextstream.h \
		/opt/qt5.12.10-arm/include/QtCore/qlocale.h \
		/opt/qt5.12.10-arm/include/QtCore/qset.h \
		/opt/qt5.12.10-arm/include/QtCore/qcontiguouscache.h \
		/opt/qt5.12.10-arm/include/QtCore/qurl.h \
		/opt/qt5.12.10-arm/include/QtCore/qurlquery.h \
		/opt/qt5.12.10-arm/include/QtCore/qfile.h \
		/opt/qt5.12.10-arm/include/QtCore/qfiledevice.h \
		/opt/qt5.12.10-arm/include/QtGui/qvector2d.h \
		/opt/qt5.12.10-arm/include/QtGui/qtouchdevice.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QListWidgetItem \
		/opt/qt5.12.10-arm/include/QtWidgets/qlistwidget.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qlistview.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qabstractitemview.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qabstractscrollarea.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qframe.h \
		/opt/qt5.12.10-arm/include/QtCore/qabstractitemmodel.h \
		/opt/qt5.12.10-arm/include/QtCore/qitemselectionmodel.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qabstractitemdelegate.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qstyleoption.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qabstractspinbox.h \
		/opt/qt5.12.10-arm/include/QtGui/qvalidator.h \
		/opt/qt5.12.10-arm/include/QtCore/qregularexpression.h \
		/opt/qt5.12.10-arm/include/QtGui/qicon.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qslider.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qabstractslider.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qstyle.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qtabbar.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qtabwidget.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qrubberband.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QVBoxLayout \
		/opt/qt5.12.10-arm/include/QtWidgets/qboxlayout.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qlayout.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qlayoutitem.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qgridlayout.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QLabel \
		/opt/qt5.12.10-arm/include/QtWidgets/qlabel.h \
		moc_predefs.h \
		/opt/qt5.12.10-arm/bin/moc
	/opt/qt5.12.10-arm/bin/moc $(DEFINES) --include /home/master/linux/my_project/moc_predefs.h -I/opt/qt5.12.10-arm/mkspecs/linux-aarch64-gnu-g++ -I/home/master/linux/my_project -I/opt/qt5.12.10-arm/include -I/opt/qt5.12.10-arm/include/QtMultimediaWidgets -I/opt/qt5.12.10-arm/include/QtMultimedia -I/opt/qt5.12.10-arm/include/QtWidgets -I/opt/qt5.12.10-arm/include/QtGui -I/opt/qt5.12.10-arm/include/QtNetwork -I/opt/qt5.12.10-arm/include/QtCore -I/usr/aarch64-linux-gnu/include/c++/9 -I/usr/aarch64-linux-gnu/include/c++/9/aarch64-linux-gnu -I/usr/aarch64-linux-gnu/include/c++/9/backward -I/usr/lib/gcc-cross/aarch64-linux-gnu/9/include -I/usr/aarch64-linux-gnu/include -I/usr/include dialog.h -o moc_dialog.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_cam.h ui_dialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_cam.h ui_dialog.h
ui_cam.h: cam.ui \
		/opt/qt5.12.10-arm/bin/uic
	/opt/qt5.12.10-arm/bin/uic cam.ui -o ui_cam.h

ui_dialog.h: dialog.ui \
		/opt/qt5.12.10-arm/bin/uic
	/opt/qt5.12.10-arm/bin/uic dialog.ui -o ui_dialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

camerathread.o: camerathread.cpp camerathread.h \
		/opt/qt5.12.10-arm/include/QtCore/QThread \
		/opt/qt5.12.10-arm/include/QtCore/qthread.h \
		/opt/qt5.12.10-arm/include/QtCore/qobject.h \
		/opt/qt5.12.10-arm/include/QtCore/qobjectdefs.h \
		/opt/qt5.12.10-arm/include/QtCore/qnamespace.h \
		/opt/qt5.12.10-arm/include/QtCore/qglobal.h \
		/opt/qt5.12.10-arm/include/QtCore/qconfig-bootstrapped.h \
		/opt/qt5.12.10-arm/include/QtCore/qconfig.h \
		/opt/qt5.12.10-arm/include/QtCore/qtcore-config.h \
		/opt/qt5.12.10-arm/include/QtCore/qsystemdetection.h \
		/opt/qt5.12.10-arm/include/QtCore/qprocessordetection.h \
		/opt/qt5.12.10-arm/include/QtCore/qcompilerdetection.h \
		/opt/qt5.12.10-arm/include/QtCore/qtypeinfo.h \
		/opt/qt5.12.10-arm/include/QtCore/qsysinfo.h \
		/opt/qt5.12.10-arm/include/QtCore/qlogging.h \
		/opt/qt5.12.10-arm/include/QtCore/qflags.h \
		/opt/qt5.12.10-arm/include/QtCore/qatomic.h \
		/opt/qt5.12.10-arm/include/QtCore/qbasicatomic.h \
		/opt/qt5.12.10-arm/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5.12.10-arm/include/QtCore/qgenericatomic.h \
		/opt/qt5.12.10-arm/include/QtCore/qatomic_cxx11.h \
		/opt/qt5.12.10-arm/include/QtCore/qatomic_msvc.h \
		/opt/qt5.12.10-arm/include/QtCore/qglobalstatic.h \
		/opt/qt5.12.10-arm/include/QtCore/qmutex.h \
		/opt/qt5.12.10-arm/include/QtCore/qnumeric.h \
		/opt/qt5.12.10-arm/include/QtCore/qversiontagging.h \
		/opt/qt5.12.10-arm/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5.12.10-arm/include/QtCore/qstring.h \
		/opt/qt5.12.10-arm/include/QtCore/qchar.h \
		/opt/qt5.12.10-arm/include/QtCore/qbytearray.h \
		/opt/qt5.12.10-arm/include/QtCore/qrefcount.h \
		/opt/qt5.12.10-arm/include/QtCore/qarraydata.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringliteral.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringalgorithms.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringview.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringbuilder.h \
		/opt/qt5.12.10-arm/include/QtCore/qlist.h \
		/opt/qt5.12.10-arm/include/QtCore/qalgorithms.h \
		/opt/qt5.12.10-arm/include/QtCore/qiterator.h \
		/opt/qt5.12.10-arm/include/QtCore/qhashfunctions.h \
		/opt/qt5.12.10-arm/include/QtCore/qpair.h \
		/opt/qt5.12.10-arm/include/QtCore/qbytearraylist.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringlist.h \
		/opt/qt5.12.10-arm/include/QtCore/qregexp.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringmatcher.h \
		/opt/qt5.12.10-arm/include/QtCore/qcoreevent.h \
		/opt/qt5.12.10-arm/include/QtCore/qscopedpointer.h \
		/opt/qt5.12.10-arm/include/QtCore/qmetatype.h \
		/opt/qt5.12.10-arm/include/QtCore/qvarlengtharray.h \
		/opt/qt5.12.10-arm/include/QtCore/qcontainerfwd.h \
		/opt/qt5.12.10-arm/include/QtCore/qobject_impl.h \
		/opt/qt5.12.10-arm/include/QtGui/QImage \
		/opt/qt5.12.10-arm/include/QtGui/qimage.h \
		/opt/qt5.12.10-arm/include/QtGui/qtguiglobal.h \
		/opt/qt5.12.10-arm/include/QtGui/qtgui-config.h \
		/opt/qt5.12.10-arm/include/QtGui/qcolor.h \
		/opt/qt5.12.10-arm/include/QtGui/qrgb.h \
		/opt/qt5.12.10-arm/include/QtGui/qrgba64.h \
		/opt/qt5.12.10-arm/include/QtGui/qpaintdevice.h \
		/opt/qt5.12.10-arm/include/QtGui/qwindowdefs.h \
		/opt/qt5.12.10-arm/include/QtGui/qwindowdefs_win.h \
		/opt/qt5.12.10-arm/include/QtCore/qrect.h \
		/opt/qt5.12.10-arm/include/QtCore/qmargins.h \
		/opt/qt5.12.10-arm/include/QtCore/qsize.h \
		/opt/qt5.12.10-arm/include/QtCore/qpoint.h \
		/opt/qt5.12.10-arm/include/QtGui/qpixelformat.h \
		/opt/qt5.12.10-arm/include/QtGui/qtransform.h \
		/opt/qt5.12.10-arm/include/QtGui/qmatrix.h \
		/opt/qt5.12.10-arm/include/QtGui/qpolygon.h \
		/opt/qt5.12.10-arm/include/QtCore/qvector.h \
		/opt/qt5.12.10-arm/include/QtGui/qregion.h \
		/opt/qt5.12.10-arm/include/QtCore/qdatastream.h \
		/opt/qt5.12.10-arm/include/QtCore/qiodevice.h \
		/opt/qt5.12.10-arm/include/QtCore/qline.h \
		/opt/qt5.12.10-arm/include/QtGui/qpainterpath.h \
		v4l2_app.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camerathread.o camerathread.cpp

dialog.o: dialog.cpp dialog.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QDialog \
		/opt/qt5.12.10-arm/include/QtWidgets/qdialog.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qtwidgetsglobal.h \
		/opt/qt5.12.10-arm/include/QtGui/qtguiglobal.h \
		/opt/qt5.12.10-arm/include/QtCore/qglobal.h \
		/opt/qt5.12.10-arm/include/QtCore/qconfig-bootstrapped.h \
		/opt/qt5.12.10-arm/include/QtCore/qconfig.h \
		/opt/qt5.12.10-arm/include/QtCore/qtcore-config.h \
		/opt/qt5.12.10-arm/include/QtCore/qsystemdetection.h \
		/opt/qt5.12.10-arm/include/QtCore/qprocessordetection.h \
		/opt/qt5.12.10-arm/include/QtCore/qcompilerdetection.h \
		/opt/qt5.12.10-arm/include/QtCore/qtypeinfo.h \
		/opt/qt5.12.10-arm/include/QtCore/qsysinfo.h \
		/opt/qt5.12.10-arm/include/QtCore/qlogging.h \
		/opt/qt5.12.10-arm/include/QtCore/qflags.h \
		/opt/qt5.12.10-arm/include/QtCore/qatomic.h \
		/opt/qt5.12.10-arm/include/QtCore/qbasicatomic.h \
		/opt/qt5.12.10-arm/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5.12.10-arm/include/QtCore/qgenericatomic.h \
		/opt/qt5.12.10-arm/include/QtCore/qatomic_cxx11.h \
		/opt/qt5.12.10-arm/include/QtCore/qatomic_msvc.h \
		/opt/qt5.12.10-arm/include/QtCore/qglobalstatic.h \
		/opt/qt5.12.10-arm/include/QtCore/qmutex.h \
		/opt/qt5.12.10-arm/include/QtCore/qnumeric.h \
		/opt/qt5.12.10-arm/include/QtCore/qversiontagging.h \
		/opt/qt5.12.10-arm/include/QtGui/qtgui-config.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qtwidgets-config.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qwidget.h \
		/opt/qt5.12.10-arm/include/QtGui/qwindowdefs.h \
		/opt/qt5.12.10-arm/include/QtCore/qobjectdefs.h \
		/opt/qt5.12.10-arm/include/QtCore/qnamespace.h \
		/opt/qt5.12.10-arm/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5.12.10-arm/include/QtGui/qwindowdefs_win.h \
		/opt/qt5.12.10-arm/include/QtCore/qobject.h \
		/opt/qt5.12.10-arm/include/QtCore/qstring.h \
		/opt/qt5.12.10-arm/include/QtCore/qchar.h \
		/opt/qt5.12.10-arm/include/QtCore/qbytearray.h \
		/opt/qt5.12.10-arm/include/QtCore/qrefcount.h \
		/opt/qt5.12.10-arm/include/QtCore/qarraydata.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringliteral.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringalgorithms.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringview.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringbuilder.h \
		/opt/qt5.12.10-arm/include/QtCore/qlist.h \
		/opt/qt5.12.10-arm/include/QtCore/qalgorithms.h \
		/opt/qt5.12.10-arm/include/QtCore/qiterator.h \
		/opt/qt5.12.10-arm/include/QtCore/qhashfunctions.h \
		/opt/qt5.12.10-arm/include/QtCore/qpair.h \
		/opt/qt5.12.10-arm/include/QtCore/qbytearraylist.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringlist.h \
		/opt/qt5.12.10-arm/include/QtCore/qregexp.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringmatcher.h \
		/opt/qt5.12.10-arm/include/QtCore/qcoreevent.h \
		/opt/qt5.12.10-arm/include/QtCore/qscopedpointer.h \
		/opt/qt5.12.10-arm/include/QtCore/qmetatype.h \
		/opt/qt5.12.10-arm/include/QtCore/qvarlengtharray.h \
		/opt/qt5.12.10-arm/include/QtCore/qcontainerfwd.h \
		/opt/qt5.12.10-arm/include/QtCore/qobject_impl.h \
		/opt/qt5.12.10-arm/include/QtCore/qmargins.h \
		/opt/qt5.12.10-arm/include/QtGui/qpaintdevice.h \
		/opt/qt5.12.10-arm/include/QtCore/qrect.h \
		/opt/qt5.12.10-arm/include/QtCore/qsize.h \
		/opt/qt5.12.10-arm/include/QtCore/qpoint.h \
		/opt/qt5.12.10-arm/include/QtGui/qpalette.h \
		/opt/qt5.12.10-arm/include/QtGui/qcolor.h \
		/opt/qt5.12.10-arm/include/QtGui/qrgb.h \
		/opt/qt5.12.10-arm/include/QtGui/qrgba64.h \
		/opt/qt5.12.10-arm/include/QtGui/qbrush.h \
		/opt/qt5.12.10-arm/include/QtCore/qvector.h \
		/opt/qt5.12.10-arm/include/QtGui/qmatrix.h \
		/opt/qt5.12.10-arm/include/QtGui/qpolygon.h \
		/opt/qt5.12.10-arm/include/QtGui/qregion.h \
		/opt/qt5.12.10-arm/include/QtCore/qdatastream.h \
		/opt/qt5.12.10-arm/include/QtCore/qiodevice.h \
		/opt/qt5.12.10-arm/include/QtCore/qline.h \
		/opt/qt5.12.10-arm/include/QtGui/qtransform.h \
		/opt/qt5.12.10-arm/include/QtGui/qpainterpath.h \
		/opt/qt5.12.10-arm/include/QtGui/qimage.h \
		/opt/qt5.12.10-arm/include/QtGui/qpixelformat.h \
		/opt/qt5.12.10-arm/include/QtGui/qpixmap.h \
		/opt/qt5.12.10-arm/include/QtCore/qsharedpointer.h \
		/opt/qt5.12.10-arm/include/QtCore/qshareddata.h \
		/opt/qt5.12.10-arm/include/QtCore/qhash.h \
		/opt/qt5.12.10-arm/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5.12.10-arm/include/QtGui/qfont.h \
		/opt/qt5.12.10-arm/include/QtGui/qfontmetrics.h \
		/opt/qt5.12.10-arm/include/QtGui/qfontinfo.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qsizepolicy.h \
		/opt/qt5.12.10-arm/include/QtGui/qcursor.h \
		/opt/qt5.12.10-arm/include/QtGui/qkeysequence.h \
		/opt/qt5.12.10-arm/include/QtGui/qevent.h \
		/opt/qt5.12.10-arm/include/QtCore/qvariant.h \
		/opt/qt5.12.10-arm/include/QtCore/qmap.h \
		/opt/qt5.12.10-arm/include/QtCore/qdebug.h \
		/opt/qt5.12.10-arm/include/QtCore/qtextstream.h \
		/opt/qt5.12.10-arm/include/QtCore/qlocale.h \
		/opt/qt5.12.10-arm/include/QtCore/qset.h \
		/opt/qt5.12.10-arm/include/QtCore/qcontiguouscache.h \
		/opt/qt5.12.10-arm/include/QtCore/qurl.h \
		/opt/qt5.12.10-arm/include/QtCore/qurlquery.h \
		/opt/qt5.12.10-arm/include/QtCore/qfile.h \
		/opt/qt5.12.10-arm/include/QtCore/qfiledevice.h \
		/opt/qt5.12.10-arm/include/QtGui/qvector2d.h \
		/opt/qt5.12.10-arm/include/QtGui/qtouchdevice.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QListWidgetItem \
		/opt/qt5.12.10-arm/include/QtWidgets/qlistwidget.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qlistview.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qabstractitemview.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qabstractscrollarea.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qframe.h \
		/opt/qt5.12.10-arm/include/QtCore/qabstractitemmodel.h \
		/opt/qt5.12.10-arm/include/QtCore/qitemselectionmodel.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qabstractitemdelegate.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qstyleoption.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qabstractspinbox.h \
		/opt/qt5.12.10-arm/include/QtGui/qvalidator.h \
		/opt/qt5.12.10-arm/include/QtCore/qregularexpression.h \
		/opt/qt5.12.10-arm/include/QtGui/qicon.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qslider.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qabstractslider.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qstyle.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qtabbar.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qtabwidget.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qrubberband.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QVBoxLayout \
		/opt/qt5.12.10-arm/include/QtWidgets/qboxlayout.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qlayout.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qlayoutitem.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qgridlayout.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QLabel \
		/opt/qt5.12.10-arm/include/QtWidgets/qlabel.h \
		ui_dialog.h \
		/opt/qt5.12.10-arm/include/QtCore/QVariant \
		/opt/qt5.12.10-arm/include/QtWidgets/QApplication \
		/opt/qt5.12.10-arm/include/QtWidgets/qapplication.h \
		/opt/qt5.12.10-arm/include/QtCore/qcoreapplication.h \
		/opt/qt5.12.10-arm/include/QtCore/qeventloop.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qdesktopwidget.h \
		/opt/qt5.12.10-arm/include/QtGui/qguiapplication.h \
		/opt/qt5.12.10-arm/include/QtGui/qinputmethod.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QPushButton \
		/opt/qt5.12.10-arm/include/QtWidgets/qpushbutton.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qabstractbutton.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QScrollArea \
		/opt/qt5.12.10-arm/include/QtWidgets/qscrollarea.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QWidget \
		cam.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/QCamera \
		/opt/qt5.12.10-arm/include/QtMultimedia/qcamera.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qmediacontrol.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qtmultimediaglobal.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qtmultimedia-config.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qmediaobject.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qmultimedia.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qmediaservice.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qcameraexposure.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qmediaenumdebug.h \
		/opt/qt5.12.10-arm/include/QtCore/qmetaobject.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qcamerafocus.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qcameraimageprocessing.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qcameraviewfindersettings.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qvideoframe.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qabstractvideobuffer.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/QCameraImageCapture \
		/opt/qt5.12.10-arm/include/QtMultimedia/qcameraimagecapture.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qmediaencodersettings.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qmediabindableinterface.h \
		/opt/qt5.12.10-arm/include/QtMultimediaWidgets/QVideoWidget \
		/opt/qt5.12.10-arm/include/QtMultimediaWidgets/qvideowidget.h \
		/opt/qt5.12.10-arm/include/QtMultimediaWidgets/qtmultimediawidgetdefs.h \
		/opt/qt5.12.10-arm/include/QtCore/QDateTime \
		/opt/qt5.12.10-arm/include/QtCore/qdatetime.h \
		/opt/qt5.12.10-arm/include/QtCore/QDir \
		/opt/qt5.12.10-arm/include/QtCore/qdir.h \
		/opt/qt5.12.10-arm/include/QtCore/qfileinfo.h \
		/opt/qt5.12.10-arm/include/QtCore/QTimer \
		/opt/qt5.12.10-arm/include/QtCore/qtimer.h \
		/opt/qt5.12.10-arm/include/QtCore/qbasictimer.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/QVideoProbe \
		/opt/qt5.12.10-arm/include/QtMultimedia/qvideoprobe.h \
		/opt/qt5.12.10-arm/include/QtCore/QObject \
		/opt/qt5.12.10-arm/include/QtWidgets/QGraphicsScene \
		/opt/qt5.12.10-arm/include/QtWidgets/qgraphicsscene.h \
		/opt/qt5.12.10-arm/include/QtGui/qpen.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QGraphicsView \
		/opt/qt5.12.10-arm/include/QtWidgets/qgraphicsview.h \
		/opt/qt5.12.10-arm/include/QtGui/qpainter.h \
		/opt/qt5.12.10-arm/include/QtGui/qtextoption.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QGraphicsProxyWidget \
		/opt/qt5.12.10-arm/include/QtWidgets/qgraphicsproxywidget.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qgraphicswidget.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qgraphicslayoutitem.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qgraphicsitem.h \
		/opt/qt5.12.10-arm/include/QtMultimediaWidgets/QGraphicsVideoItem \
		/opt/qt5.12.10-arm/include/QtMultimediaWidgets/qgraphicsvideoitem.h \
		camerathread.h \
		/opt/qt5.12.10-arm/include/QtCore/QThread \
		/opt/qt5.12.10-arm/include/QtCore/qthread.h \
		/opt/qt5.12.10-arm/include/QtGui/QImage
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

main.o: main.cpp cam.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QWidget \
		/opt/qt5.12.10-arm/include/QtWidgets/qwidget.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qtwidgetsglobal.h \
		/opt/qt5.12.10-arm/include/QtGui/qtguiglobal.h \
		/opt/qt5.12.10-arm/include/QtCore/qglobal.h \
		/opt/qt5.12.10-arm/include/QtCore/qconfig-bootstrapped.h \
		/opt/qt5.12.10-arm/include/QtCore/qconfig.h \
		/opt/qt5.12.10-arm/include/QtCore/qtcore-config.h \
		/opt/qt5.12.10-arm/include/QtCore/qsystemdetection.h \
		/opt/qt5.12.10-arm/include/QtCore/qprocessordetection.h \
		/opt/qt5.12.10-arm/include/QtCore/qcompilerdetection.h \
		/opt/qt5.12.10-arm/include/QtCore/qtypeinfo.h \
		/opt/qt5.12.10-arm/include/QtCore/qsysinfo.h \
		/opt/qt5.12.10-arm/include/QtCore/qlogging.h \
		/opt/qt5.12.10-arm/include/QtCore/qflags.h \
		/opt/qt5.12.10-arm/include/QtCore/qatomic.h \
		/opt/qt5.12.10-arm/include/QtCore/qbasicatomic.h \
		/opt/qt5.12.10-arm/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5.12.10-arm/include/QtCore/qgenericatomic.h \
		/opt/qt5.12.10-arm/include/QtCore/qatomic_cxx11.h \
		/opt/qt5.12.10-arm/include/QtCore/qatomic_msvc.h \
		/opt/qt5.12.10-arm/include/QtCore/qglobalstatic.h \
		/opt/qt5.12.10-arm/include/QtCore/qmutex.h \
		/opt/qt5.12.10-arm/include/QtCore/qnumeric.h \
		/opt/qt5.12.10-arm/include/QtCore/qversiontagging.h \
		/opt/qt5.12.10-arm/include/QtGui/qtgui-config.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qtwidgets-config.h \
		/opt/qt5.12.10-arm/include/QtGui/qwindowdefs.h \
		/opt/qt5.12.10-arm/include/QtCore/qobjectdefs.h \
		/opt/qt5.12.10-arm/include/QtCore/qnamespace.h \
		/opt/qt5.12.10-arm/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5.12.10-arm/include/QtGui/qwindowdefs_win.h \
		/opt/qt5.12.10-arm/include/QtCore/qobject.h \
		/opt/qt5.12.10-arm/include/QtCore/qstring.h \
		/opt/qt5.12.10-arm/include/QtCore/qchar.h \
		/opt/qt5.12.10-arm/include/QtCore/qbytearray.h \
		/opt/qt5.12.10-arm/include/QtCore/qrefcount.h \
		/opt/qt5.12.10-arm/include/QtCore/qarraydata.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringliteral.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringalgorithms.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringview.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringbuilder.h \
		/opt/qt5.12.10-arm/include/QtCore/qlist.h \
		/opt/qt5.12.10-arm/include/QtCore/qalgorithms.h \
		/opt/qt5.12.10-arm/include/QtCore/qiterator.h \
		/opt/qt5.12.10-arm/include/QtCore/qhashfunctions.h \
		/opt/qt5.12.10-arm/include/QtCore/qpair.h \
		/opt/qt5.12.10-arm/include/QtCore/qbytearraylist.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringlist.h \
		/opt/qt5.12.10-arm/include/QtCore/qregexp.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringmatcher.h \
		/opt/qt5.12.10-arm/include/QtCore/qcoreevent.h \
		/opt/qt5.12.10-arm/include/QtCore/qscopedpointer.h \
		/opt/qt5.12.10-arm/include/QtCore/qmetatype.h \
		/opt/qt5.12.10-arm/include/QtCore/qvarlengtharray.h \
		/opt/qt5.12.10-arm/include/QtCore/qcontainerfwd.h \
		/opt/qt5.12.10-arm/include/QtCore/qobject_impl.h \
		/opt/qt5.12.10-arm/include/QtCore/qmargins.h \
		/opt/qt5.12.10-arm/include/QtGui/qpaintdevice.h \
		/opt/qt5.12.10-arm/include/QtCore/qrect.h \
		/opt/qt5.12.10-arm/include/QtCore/qsize.h \
		/opt/qt5.12.10-arm/include/QtCore/qpoint.h \
		/opt/qt5.12.10-arm/include/QtGui/qpalette.h \
		/opt/qt5.12.10-arm/include/QtGui/qcolor.h \
		/opt/qt5.12.10-arm/include/QtGui/qrgb.h \
		/opt/qt5.12.10-arm/include/QtGui/qrgba64.h \
		/opt/qt5.12.10-arm/include/QtGui/qbrush.h \
		/opt/qt5.12.10-arm/include/QtCore/qvector.h \
		/opt/qt5.12.10-arm/include/QtGui/qmatrix.h \
		/opt/qt5.12.10-arm/include/QtGui/qpolygon.h \
		/opt/qt5.12.10-arm/include/QtGui/qregion.h \
		/opt/qt5.12.10-arm/include/QtCore/qdatastream.h \
		/opt/qt5.12.10-arm/include/QtCore/qiodevice.h \
		/opt/qt5.12.10-arm/include/QtCore/qline.h \
		/opt/qt5.12.10-arm/include/QtGui/qtransform.h \
		/opt/qt5.12.10-arm/include/QtGui/qpainterpath.h \
		/opt/qt5.12.10-arm/include/QtGui/qimage.h \
		/opt/qt5.12.10-arm/include/QtGui/qpixelformat.h \
		/opt/qt5.12.10-arm/include/QtGui/qpixmap.h \
		/opt/qt5.12.10-arm/include/QtCore/qsharedpointer.h \
		/opt/qt5.12.10-arm/include/QtCore/qshareddata.h \
		/opt/qt5.12.10-arm/include/QtCore/qhash.h \
		/opt/qt5.12.10-arm/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5.12.10-arm/include/QtGui/qfont.h \
		/opt/qt5.12.10-arm/include/QtGui/qfontmetrics.h \
		/opt/qt5.12.10-arm/include/QtGui/qfontinfo.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qsizepolicy.h \
		/opt/qt5.12.10-arm/include/QtGui/qcursor.h \
		/opt/qt5.12.10-arm/include/QtGui/qkeysequence.h \
		/opt/qt5.12.10-arm/include/QtGui/qevent.h \
		/opt/qt5.12.10-arm/include/QtCore/qvariant.h \
		/opt/qt5.12.10-arm/include/QtCore/qmap.h \
		/opt/qt5.12.10-arm/include/QtCore/qdebug.h \
		/opt/qt5.12.10-arm/include/QtCore/qtextstream.h \
		/opt/qt5.12.10-arm/include/QtCore/qlocale.h \
		/opt/qt5.12.10-arm/include/QtCore/qset.h \
		/opt/qt5.12.10-arm/include/QtCore/qcontiguouscache.h \
		/opt/qt5.12.10-arm/include/QtCore/qurl.h \
		/opt/qt5.12.10-arm/include/QtCore/qurlquery.h \
		/opt/qt5.12.10-arm/include/QtCore/qfile.h \
		/opt/qt5.12.10-arm/include/QtCore/qfiledevice.h \
		/opt/qt5.12.10-arm/include/QtGui/qvector2d.h \
		/opt/qt5.12.10-arm/include/QtGui/qtouchdevice.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/QCamera \
		/opt/qt5.12.10-arm/include/QtMultimedia/qcamera.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qmediacontrol.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qtmultimediaglobal.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qtmultimedia-config.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qmediaobject.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qmultimedia.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qmediaservice.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qcameraexposure.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qmediaenumdebug.h \
		/opt/qt5.12.10-arm/include/QtCore/qmetaobject.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qcamerafocus.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qcameraimageprocessing.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qcameraviewfindersettings.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qvideoframe.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qabstractvideobuffer.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/QCameraImageCapture \
		/opt/qt5.12.10-arm/include/QtMultimedia/qcameraimagecapture.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qmediaencodersettings.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qmediabindableinterface.h \
		/opt/qt5.12.10-arm/include/QtMultimediaWidgets/QVideoWidget \
		/opt/qt5.12.10-arm/include/QtMultimediaWidgets/qvideowidget.h \
		/opt/qt5.12.10-arm/include/QtMultimediaWidgets/qtmultimediawidgetdefs.h \
		/opt/qt5.12.10-arm/include/QtCore/QDateTime \
		/opt/qt5.12.10-arm/include/QtCore/qdatetime.h \
		/opt/qt5.12.10-arm/include/QtCore/QDir \
		/opt/qt5.12.10-arm/include/QtCore/qdir.h \
		/opt/qt5.12.10-arm/include/QtCore/qfileinfo.h \
		/opt/qt5.12.10-arm/include/QtCore/QTimer \
		/opt/qt5.12.10-arm/include/QtCore/qtimer.h \
		/opt/qt5.12.10-arm/include/QtCore/qbasictimer.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/QVideoProbe \
		/opt/qt5.12.10-arm/include/QtMultimedia/qvideoprobe.h \
		/opt/qt5.12.10-arm/include/QtCore/QObject \
		/opt/qt5.12.10-arm/include/QtWidgets/QGraphicsScene \
		/opt/qt5.12.10-arm/include/QtWidgets/qgraphicsscene.h \
		/opt/qt5.12.10-arm/include/QtGui/qpen.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QGraphicsView \
		/opt/qt5.12.10-arm/include/QtWidgets/qgraphicsview.h \
		/opt/qt5.12.10-arm/include/QtGui/qpainter.h \
		/opt/qt5.12.10-arm/include/QtGui/qtextoption.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qscrollarea.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qabstractscrollarea.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qframe.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QGraphicsProxyWidget \
		/opt/qt5.12.10-arm/include/QtWidgets/qgraphicsproxywidget.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qgraphicswidget.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qgraphicslayoutitem.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qgraphicsitem.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QApplication \
		/opt/qt5.12.10-arm/include/QtWidgets/qapplication.h \
		/opt/qt5.12.10-arm/include/QtCore/qcoreapplication.h \
		/opt/qt5.12.10-arm/include/QtCore/qeventloop.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qdesktopwidget.h \
		/opt/qt5.12.10-arm/include/QtGui/qguiapplication.h \
		/opt/qt5.12.10-arm/include/QtGui/qinputmethod.h \
		/opt/qt5.12.10-arm/include/QtMultimediaWidgets/QGraphicsVideoItem \
		/opt/qt5.12.10-arm/include/QtMultimediaWidgets/qgraphicsvideoitem.h \
		camerathread.h \
		/opt/qt5.12.10-arm/include/QtCore/QThread \
		/opt/qt5.12.10-arm/include/QtCore/qthread.h \
		/opt/qt5.12.10-arm/include/QtGui/QImage \
		v4l2_app.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

cam.o: cam.cpp cam.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QWidget \
		/opt/qt5.12.10-arm/include/QtWidgets/qwidget.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qtwidgetsglobal.h \
		/opt/qt5.12.10-arm/include/QtGui/qtguiglobal.h \
		/opt/qt5.12.10-arm/include/QtCore/qglobal.h \
		/opt/qt5.12.10-arm/include/QtCore/qconfig-bootstrapped.h \
		/opt/qt5.12.10-arm/include/QtCore/qconfig.h \
		/opt/qt5.12.10-arm/include/QtCore/qtcore-config.h \
		/opt/qt5.12.10-arm/include/QtCore/qsystemdetection.h \
		/opt/qt5.12.10-arm/include/QtCore/qprocessordetection.h \
		/opt/qt5.12.10-arm/include/QtCore/qcompilerdetection.h \
		/opt/qt5.12.10-arm/include/QtCore/qtypeinfo.h \
		/opt/qt5.12.10-arm/include/QtCore/qsysinfo.h \
		/opt/qt5.12.10-arm/include/QtCore/qlogging.h \
		/opt/qt5.12.10-arm/include/QtCore/qflags.h \
		/opt/qt5.12.10-arm/include/QtCore/qatomic.h \
		/opt/qt5.12.10-arm/include/QtCore/qbasicatomic.h \
		/opt/qt5.12.10-arm/include/QtCore/qatomic_bootstrap.h \
		/opt/qt5.12.10-arm/include/QtCore/qgenericatomic.h \
		/opt/qt5.12.10-arm/include/QtCore/qatomic_cxx11.h \
		/opt/qt5.12.10-arm/include/QtCore/qatomic_msvc.h \
		/opt/qt5.12.10-arm/include/QtCore/qglobalstatic.h \
		/opt/qt5.12.10-arm/include/QtCore/qmutex.h \
		/opt/qt5.12.10-arm/include/QtCore/qnumeric.h \
		/opt/qt5.12.10-arm/include/QtCore/qversiontagging.h \
		/opt/qt5.12.10-arm/include/QtGui/qtgui-config.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qtwidgets-config.h \
		/opt/qt5.12.10-arm/include/QtGui/qwindowdefs.h \
		/opt/qt5.12.10-arm/include/QtCore/qobjectdefs.h \
		/opt/qt5.12.10-arm/include/QtCore/qnamespace.h \
		/opt/qt5.12.10-arm/include/QtCore/qobjectdefs_impl.h \
		/opt/qt5.12.10-arm/include/QtGui/qwindowdefs_win.h \
		/opt/qt5.12.10-arm/include/QtCore/qobject.h \
		/opt/qt5.12.10-arm/include/QtCore/qstring.h \
		/opt/qt5.12.10-arm/include/QtCore/qchar.h \
		/opt/qt5.12.10-arm/include/QtCore/qbytearray.h \
		/opt/qt5.12.10-arm/include/QtCore/qrefcount.h \
		/opt/qt5.12.10-arm/include/QtCore/qarraydata.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringliteral.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringalgorithms.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringview.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringbuilder.h \
		/opt/qt5.12.10-arm/include/QtCore/qlist.h \
		/opt/qt5.12.10-arm/include/QtCore/qalgorithms.h \
		/opt/qt5.12.10-arm/include/QtCore/qiterator.h \
		/opt/qt5.12.10-arm/include/QtCore/qhashfunctions.h \
		/opt/qt5.12.10-arm/include/QtCore/qpair.h \
		/opt/qt5.12.10-arm/include/QtCore/qbytearraylist.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringlist.h \
		/opt/qt5.12.10-arm/include/QtCore/qregexp.h \
		/opt/qt5.12.10-arm/include/QtCore/qstringmatcher.h \
		/opt/qt5.12.10-arm/include/QtCore/qcoreevent.h \
		/opt/qt5.12.10-arm/include/QtCore/qscopedpointer.h \
		/opt/qt5.12.10-arm/include/QtCore/qmetatype.h \
		/opt/qt5.12.10-arm/include/QtCore/qvarlengtharray.h \
		/opt/qt5.12.10-arm/include/QtCore/qcontainerfwd.h \
		/opt/qt5.12.10-arm/include/QtCore/qobject_impl.h \
		/opt/qt5.12.10-arm/include/QtCore/qmargins.h \
		/opt/qt5.12.10-arm/include/QtGui/qpaintdevice.h \
		/opt/qt5.12.10-arm/include/QtCore/qrect.h \
		/opt/qt5.12.10-arm/include/QtCore/qsize.h \
		/opt/qt5.12.10-arm/include/QtCore/qpoint.h \
		/opt/qt5.12.10-arm/include/QtGui/qpalette.h \
		/opt/qt5.12.10-arm/include/QtGui/qcolor.h \
		/opt/qt5.12.10-arm/include/QtGui/qrgb.h \
		/opt/qt5.12.10-arm/include/QtGui/qrgba64.h \
		/opt/qt5.12.10-arm/include/QtGui/qbrush.h \
		/opt/qt5.12.10-arm/include/QtCore/qvector.h \
		/opt/qt5.12.10-arm/include/QtGui/qmatrix.h \
		/opt/qt5.12.10-arm/include/QtGui/qpolygon.h \
		/opt/qt5.12.10-arm/include/QtGui/qregion.h \
		/opt/qt5.12.10-arm/include/QtCore/qdatastream.h \
		/opt/qt5.12.10-arm/include/QtCore/qiodevice.h \
		/opt/qt5.12.10-arm/include/QtCore/qline.h \
		/opt/qt5.12.10-arm/include/QtGui/qtransform.h \
		/opt/qt5.12.10-arm/include/QtGui/qpainterpath.h \
		/opt/qt5.12.10-arm/include/QtGui/qimage.h \
		/opt/qt5.12.10-arm/include/QtGui/qpixelformat.h \
		/opt/qt5.12.10-arm/include/QtGui/qpixmap.h \
		/opt/qt5.12.10-arm/include/QtCore/qsharedpointer.h \
		/opt/qt5.12.10-arm/include/QtCore/qshareddata.h \
		/opt/qt5.12.10-arm/include/QtCore/qhash.h \
		/opt/qt5.12.10-arm/include/QtCore/qsharedpointer_impl.h \
		/opt/qt5.12.10-arm/include/QtGui/qfont.h \
		/opt/qt5.12.10-arm/include/QtGui/qfontmetrics.h \
		/opt/qt5.12.10-arm/include/QtGui/qfontinfo.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qsizepolicy.h \
		/opt/qt5.12.10-arm/include/QtGui/qcursor.h \
		/opt/qt5.12.10-arm/include/QtGui/qkeysequence.h \
		/opt/qt5.12.10-arm/include/QtGui/qevent.h \
		/opt/qt5.12.10-arm/include/QtCore/qvariant.h \
		/opt/qt5.12.10-arm/include/QtCore/qmap.h \
		/opt/qt5.12.10-arm/include/QtCore/qdebug.h \
		/opt/qt5.12.10-arm/include/QtCore/qtextstream.h \
		/opt/qt5.12.10-arm/include/QtCore/qlocale.h \
		/opt/qt5.12.10-arm/include/QtCore/qset.h \
		/opt/qt5.12.10-arm/include/QtCore/qcontiguouscache.h \
		/opt/qt5.12.10-arm/include/QtCore/qurl.h \
		/opt/qt5.12.10-arm/include/QtCore/qurlquery.h \
		/opt/qt5.12.10-arm/include/QtCore/qfile.h \
		/opt/qt5.12.10-arm/include/QtCore/qfiledevice.h \
		/opt/qt5.12.10-arm/include/QtGui/qvector2d.h \
		/opt/qt5.12.10-arm/include/QtGui/qtouchdevice.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/QCamera \
		/opt/qt5.12.10-arm/include/QtMultimedia/qcamera.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qmediacontrol.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qtmultimediaglobal.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qtmultimedia-config.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qmediaobject.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qmultimedia.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qmediaservice.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qcameraexposure.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qmediaenumdebug.h \
		/opt/qt5.12.10-arm/include/QtCore/qmetaobject.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qcamerafocus.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qcameraimageprocessing.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qcameraviewfindersettings.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qvideoframe.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qabstractvideobuffer.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/QCameraImageCapture \
		/opt/qt5.12.10-arm/include/QtMultimedia/qcameraimagecapture.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qmediaencodersettings.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/qmediabindableinterface.h \
		/opt/qt5.12.10-arm/include/QtMultimediaWidgets/QVideoWidget \
		/opt/qt5.12.10-arm/include/QtMultimediaWidgets/qvideowidget.h \
		/opt/qt5.12.10-arm/include/QtMultimediaWidgets/qtmultimediawidgetdefs.h \
		/opt/qt5.12.10-arm/include/QtCore/QDateTime \
		/opt/qt5.12.10-arm/include/QtCore/qdatetime.h \
		/opt/qt5.12.10-arm/include/QtCore/QDir \
		/opt/qt5.12.10-arm/include/QtCore/qdir.h \
		/opt/qt5.12.10-arm/include/QtCore/qfileinfo.h \
		/opt/qt5.12.10-arm/include/QtCore/QTimer \
		/opt/qt5.12.10-arm/include/QtCore/qtimer.h \
		/opt/qt5.12.10-arm/include/QtCore/qbasictimer.h \
		/opt/qt5.12.10-arm/include/QtMultimedia/QVideoProbe \
		/opt/qt5.12.10-arm/include/QtMultimedia/qvideoprobe.h \
		/opt/qt5.12.10-arm/include/QtCore/QObject \
		/opt/qt5.12.10-arm/include/QtWidgets/QGraphicsScene \
		/opt/qt5.12.10-arm/include/QtWidgets/qgraphicsscene.h \
		/opt/qt5.12.10-arm/include/QtGui/qpen.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QGraphicsView \
		/opt/qt5.12.10-arm/include/QtWidgets/qgraphicsview.h \
		/opt/qt5.12.10-arm/include/QtGui/qpainter.h \
		/opt/qt5.12.10-arm/include/QtGui/qtextoption.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qscrollarea.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qabstractscrollarea.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qframe.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QGraphicsProxyWidget \
		/opt/qt5.12.10-arm/include/QtWidgets/qgraphicsproxywidget.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qgraphicswidget.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qgraphicslayoutitem.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qgraphicsitem.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QApplication \
		/opt/qt5.12.10-arm/include/QtWidgets/qapplication.h \
		/opt/qt5.12.10-arm/include/QtCore/qcoreapplication.h \
		/opt/qt5.12.10-arm/include/QtCore/qeventloop.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qdesktopwidget.h \
		/opt/qt5.12.10-arm/include/QtGui/qguiapplication.h \
		/opt/qt5.12.10-arm/include/QtGui/qinputmethod.h \
		/opt/qt5.12.10-arm/include/QtMultimediaWidgets/QGraphicsVideoItem \
		/opt/qt5.12.10-arm/include/QtMultimediaWidgets/qgraphicsvideoitem.h \
		camerathread.h \
		/opt/qt5.12.10-arm/include/QtCore/QThread \
		/opt/qt5.12.10-arm/include/QtCore/qthread.h \
		/opt/qt5.12.10-arm/include/QtGui/QImage \
		ui_cam.h \
		/opt/qt5.12.10-arm/include/QtCore/QVariant \
		/opt/qt5.12.10-arm/include/QtWidgets/QLabel \
		/opt/qt5.12.10-arm/include/QtWidgets/qlabel.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QPushButton \
		/opt/qt5.12.10-arm/include/QtWidgets/qpushbutton.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qabstractbutton.h \
		/opt/qt5.12.10-arm/include/QtGui/qicon.h \
		dialog.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QDialog \
		/opt/qt5.12.10-arm/include/QtWidgets/qdialog.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QListWidgetItem \
		/opt/qt5.12.10-arm/include/QtWidgets/qlistwidget.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qlistview.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qabstractitemview.h \
		/opt/qt5.12.10-arm/include/QtCore/qabstractitemmodel.h \
		/opt/qt5.12.10-arm/include/QtCore/qitemselectionmodel.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qabstractitemdelegate.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qstyleoption.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qabstractspinbox.h \
		/opt/qt5.12.10-arm/include/QtGui/qvalidator.h \
		/opt/qt5.12.10-arm/include/QtCore/qregularexpression.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qslider.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qabstractslider.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qstyle.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qtabbar.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qtabwidget.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qrubberband.h \
		/opt/qt5.12.10-arm/include/QtWidgets/QVBoxLayout \
		/opt/qt5.12.10-arm/include/QtWidgets/qboxlayout.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qlayout.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qlayoutitem.h \
		/opt/qt5.12.10-arm/include/QtWidgets/qgridlayout.h \
		/opt/qt5.12.10-arm/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cam.o cam.cpp

v4l2_app.o: v4l2_app.c v4l2_app.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o v4l2_app.o v4l2_app.c

moc_cam.o: moc_cam.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cam.o moc_cam.cpp

moc_camerathread.o: moc_camerathread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_camerathread.o moc_camerathread.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/my_project/bin || mkdir -p $(INSTALL_ROOT)/opt/my_project/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/my_project/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/my_project/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/my_project/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/my_project/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

